# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: We Go South
email: micheltol@gmail.com
description: > # this means to ignore newlines until "baseurl:"
              Website over onze reizen naar o.a. Zuid Afrika & Costa Rica.
  
  
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.wegosouth.nl" # the base hostname & protocol for your site

#sidebar
default-image: countdown.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: Michel Tol
copyright:
  name: We Go South
  link: 'https://www.wegosouth.nl'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 9
paginate_path: /page:num/
include: ["_pages", "fonts"]

# Comments
disqus-shortname: micheltol
fb-page-url: https://www.facebook.com/wegosouth
fb-page-title: We go South
fb-app-id:  549480635219583
insta-page-url: https://www.instagram.com/wegosouth/
youtube-page-url: https://www.youtube.com/channel/UCr75oAWsdJyDrPAziBxQ6qw

mapbox:
  public_token: pk.eyJ1IjoibWljaGVsdG9sIiwiYSI6ImNqM3BraWYxdDAwM2MzM28yZ3lvcjRiZGcifQ.NAF8bQC04dLh7ILuirXXwQ

# Sass style
sass:
  style: compressed

# Ruby Gems
# gems: [jekyll-paginate, jekyll-seo-tag, jemoji]
plugins: [jekyll-paginate, jemoji]
# jekyll-maps

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - bundle/gems/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - start.cmd
  - Dockerfile
